services:
    github.endpoint.statuses:
        class: InkApplications\SignOff\Api\GitHub\StatusEndpoint
        arguments:
            - @github.api.statuses

    github.api.client:
        class: Github\Client
        factory:
            - InkApplications\SignOff\Api\GitHub\ApiFactory
            - createAuthenticatedApi
        arguments:
            - %github_api_key%

    github.api.statuses:
        class: Github\Api\Repository\Statuses
        factory:
            - InkApplications\SignOff\Api\GitHub\ApiFactory
            - createStatusesApi
        arguments:
            - @github.api.client
